apiVersion: v1               # Versión de la API de Kubernetes para el recurso Service
kind: Service                 # Especifica que se está creando un recurso de tipo Service
metadata:
  name: mi-servicio           # Nombre del servicio
  namespace: vallegrande      # Espacio de nombres en el que se creará el servicio
spec:
  selector:
    app: mi-app               # Selector que indica los Pods a los que se enviarán las solicitudes (aquellos que tengan esta etiqueta)
  ports:
    - protocol: TCP           # Protocolo de comunicación, en este caso TCP
      port: 80                # Puerto en el que el servicio estará disponible
      targetPort: 8085        # Puerto al que se enviará el tráfico en el contenedor
  type: NodePort              # Tipo de servicio, expone el servicio en un puerto del nodo
                                                    